version: 2.1
jobs:
  build_image:
    machine: true

    steps:
      - checkout
      - run:
         name: Build Docker image
         command: | 
           docker build -t a1zk/spg:0.1.$CIRCLE_BUILD_NUM .
           docker tag a1zk/spg:0.1.$CIRCLE_BUILD_NUM a1zk/spg:latest

      - run:
         name: Push to Dockerhub
         command: |
           docker login -u $DOCKER_LOGIN -p $DOCKER_PASS
           docker push a1zk/spg:0.1.$CIRCLE_BUILD_NUM
           docker push a1zk/spg:latest
  test:
    docker:
      - image: circleci/python:3.7
    steps:
      - checkout
      - run:
         name: Install dependency
         command: pip install -r requirements.txt
      
      - run:
         name: Running test
         command: python manage.py test -v 2
workflows:
  test_and_build_image:
    jobs:
      - build_image:
          requires:
            - test
      - test
